name: PR Analysis Bot

on:
  repository_dispatch:
    types: [pr-opened, pr-updated]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number to analyze'
        required: true
        type: number
      repo_owner:
        description: 'Repository Owner'
        required: true
        type: string
      repo_name:
        description: 'Repository Name'
        required: true
        type: string

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests groq python-dotenv
        
    - name: Create .env file
      run: |
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
        echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
        echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env
        echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}" >> .env
        echo "DISCORD_USER_ID=${{ secrets.DISCORD_USER_ID }}" >> .env
        
    - name: Run PR Analysis (Repository Dispatch)
      if: github.event_name == 'repository_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.client_payload.pr_number }}
        REPO_OWNER: ${{ github.event.client_payload.repo_owner }}
        REPO_NAME: ${{ github.event.client_payload.repo_name }}
      run: |
        python main_workflow.py
        
    - name: Run PR Analysis (Manual Dispatch)
      if: github.event_name == 'workflow_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.inputs.pr_number }}
        REPO_OWNER: ${{ github.event.inputs.repo_owner }}
        REPO_NAME: ${{ github.event.inputs.repo_name }}
      run: |
        python main_workflow.py
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pr-analysis-logs
        path: |
          *.log
          pr_analysis_*.txt
        retention-days: 7